#!/bin/sh
echo $OSTYPE

OS=$OSTYPE
PREV_COMMIT=$1
POST_COMMIT=$2
TYPE=$3

echo $OS
  if grep -q  "darwin" <<< "$OS"; then
    echo "Mac"
  else
    echo "Not Mac"
  fi

if [ TYPE != 0 ]; then
  if [ OS == "darwin19" ]; then
    echo "Mac"
  fi
#  if test -f .env.defaults; then
#    rm .env.defaults
#  fi
#  keybase fs cp --force /keybase/team/zapshot.api/helium-api/.env.defaults .
fi
