version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  aws-ecr/build_and_push_image:
    account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
    aws-access-key-id: ${AWS_ACCESS_KEY_ID}
    aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    repo: coach-tools-backend
    create-repo: true
    region: ${AWS_DEFAULT_REGION}
    tag: ${CIRCLE_SHA1}

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - aws-ecr/build_and_push_image:

      